docker-library/httpd

- 2.2/Dockerfile
- 2.4/Dockerfile
Fixes #1
Since I removed build-essential, this also happens to save tons of space.
```console
REPOSITORY          TAG                 IMAGE ID            CREATED             VIRTUAL SIZE
httpd               2.4-ssl             61a402dc6997        5 minutes ago       159.1 MB
httpd               2.2-ssl             4be0f1f6fa6b        19 minutes ago      150.2 MB
httpd               2.4                 8a43cfbafc48        8 days ago          325.6 MB
httpd               2.2                 a39e6e537500        8 days ago          316.9 MB
```
> Add ssl support, simplify build deps

- 2.2/Dockerfile
- 2.4/Dockerfile
- move to "high-availability" [subset](https://sks-keyservers.net/overview-of-pools.php#pool_ha).
related: https://github.com/docker-library/php/pull/92
> More resilient gpg getting

- 2.2/Dockerfile
- 2.4/Dockerfile
Fixes #6
Here are the mods we get, where previously the default of `2.2` was nothing: 
```console
$ docker run -it --rm new-httpd-2.2 ls modules/
httpd.exp		mod_authz_user.so  mod_include.so
mod_actions.so		mod_autoindex.so   mod_info.so
mod_alias.so		mod_cgi.so	   mod_log_config.so
mod_asis.so		mod_dav.so	   mod_logio.so
mod_auth_basic.so	mod_dav_fs.so	   mod_mime.so
mod_auth_digest.so	mod_dbd.so	   mod_negotiation.so
mod_authn_anon.so	mod_deflate.so	   mod_reqtimeout.so
mod_authn_dbd.so	mod_dir.so	   mod_rewrite.so
mod_authn_dbm.so	mod_dumpio.so	   mod_setenvif.so
mod_authn_default.so	mod_env.so	   mod_speling.so
mod_authn_file.so	mod_expires.so	   mod_ssl.so
mod_authz_dbm.so	mod_ext_filter.so  mod_status.so
mod_authz_default.so	mod_filter.so	   mod_substitute.so
mod_authz_groupfile.so …
```
> enable `most` mods on 2.2 (which is the default in 2.4)

- 2.2/Dockerfile
- 2.4/Dockerfile
See also docker-library/official-images#1420.
> Fix "gpg" usage to stop relying on deprecated and insecure behavior

- 2.4/Dockerfile
This PR updates the Dockerfile, adding libaprutil1-ldap in support of mod_ldap for Apache 2.4 LDAP integration.
Fixes #18
> Add libaprutil1-ldap closing issue 18 and adding support for mod_ldap

- 2.2/Dockerfile
- 2.4/Dockerfile
As pointed out by #13, `most` does not actually contain all the useful mods that are available in httpd.  I change my stance on compiling all the mods since they cannot be easily added later. 
The size change is negligible:
```console
REPOSITORY          TAG                 IMAGE ID            CREATED              VIRTUAL SIZE
new-httpd           2.4                 78e26c9fafcc        About a minute ago   195 MB
new-httpd           2.2                 607dafaa1442        4 minutes ago        185.7 MB
httpd               2.4                 9e510755f4bc        4 days ago          194.5 MB
httpd               2.2                 03a2da88c612        4 days ago          185 MB
```
Here are all the mods that are not in the current version:
```console
$ comm -13 <(docker run --rm httpd:2.2 ls …
```
> Build all the mods

- 2.2/Dockerfile
- 2.2/alpine/Dockerfile
Apache 2.2 does not support this compile arg `--enable-mods-shared=reallyall`. So I copy the right compile args from the tag `2.2`.
Then I remove the useless dirs `build, man, manual` for  reducing the image size:
Before: 92.06 MB
After: 80.92 MB
> Copy 2.2-alpine compile args from 2.2, and remove useless dirs.

- 2.4/Dockerfile
- 2.4/alpine/Dockerfile
- update.sh
Fixes #33.
`mod_http2` is only available in 2.4.17 and later. https://httpd.apache.org/docs/2.4/mod/mod_http2.html
> Add support for mod_http2 mod_lua mod_proxy_html mod_xml2enc

- 2.4/Dockerfile
- update.sh
Fixes #42.
```console
$ curl -v --http2 https://server-with-h2-and-ssl
...
* ALPN, offering h2
* ALPN, offering http/1.1
* SSL connection using TLS1.2 / ECDHE_RSA_AES_256_GCM_SHA384
* ALPN, server accepted to use h2
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
```
> Fix http2 support on 2.4 in debian by using newer OpenSSL 1.0.2+

- 2.2/Dockerfile
- 2.2/alpine/Dockerfile
- 2.4/Dockerfile
- 2.4/alpine/Dockerfile
This is along the same lines as:
- https://github.com/jessfraz/irssi/pull/14
- https://github.com/docker-library/php/pull/429
- https://github.com/docker-library/postgres/pull/284
- https://github.com/docker-library/python/pull/198
- https://github.com/docker-library/ruby/pull/127
- https://github.com/docker-library/tomcat/pull/70
- https://github.com/docker-library/memcached/pull/13
- https://github.com/tianon/docker-bash/pull/3
> Add explicit "--build" to our "./configure" invocations

- 2.4/alpine/Dockerfile
Fixes #50 (2.2 cannot be updated, see comment in [the Dockerfile](https://github.com/docker-library/httpd/blob/6e4544875f3f12052f8b5fd4990150cc48a59379/2.2/alpine/Dockerfile#L1-L4)).
> Bump 2.4 to use alpine 3.6

- 2.4/alpine/Dockerfile
Closes https://github.com/docker-library/httpd/issues/64
> add apr-util-ldap package to httpd:2.4-alpine (for LDAP authentication)

- 2.4/alpine/Dockerfile
See https://github.com/docker-library/httpd/pull/57 for the previous discussion about this bump and https://bz.apache.org/bugzilla/show_bug.cgi?id=61184 for upstream's discussion of it (where they're also discussing an official patch for the libressl vs openssl issue we're seeing).
> Update to 2.4.27 (alpine)

- 2.2/alpine/Dockerfile
- 2.4/alpine/Dockerfile
Copying the improvement from https://github.com/docker-library/ruby/pull/161.  Should be no discernible change in packages installed, but does make the sub-shell a little easier to understand.
> Adjust scanelf to properly detect runDeps

- 2.2/Dockerfile
- 2.2/alpine/Dockerfile
- 2.4/Dockerfile
- 2.4/alpine/Dockerfile
- update.sh
Poll Apache official patch site/tree in update.sh for potential
patches to apply to the selected release.  Update Dockerfile
RUN stanzas to directly include logic for downloading, verifying
and applying these patches.
Verification limited to checksum generated during update.sh run
as no official mechanism/signing appears to be in place for the
patches themselves.
Closes #75
> Add support for applying patches.

- 2.4/Dockerfile
- 2.4/alpine/Dockerfile
> Build all MPMs as shared modules

- 2.4/alpine/Dockerfile
> Update to Alpine 3.9

- 2.4/Dockerfile
- 2.4/alpine/Dockerfile
- `libbrotli-dev` for `mod_brotli`
- `libjansson` and `libcurl` for `mod_md`
- ~**TODO** add these to alpine?~
Broli fix is currently Debian only, since the brotli library is only in `edge` on Alpine. Libraries for `mod_md` added to Debian and Alpine.
```console
$ docker build 2.4/
....
checking whether to enable mod_brotli... checking dependencies
checking for Brotli library >= 0.6.0 via pkg-config... yes
setting MOD_BROTLI_LDADD to "-lbrotlienc"
adding "-export-symbols-regex" to MOD_BROTLI_LDADD
adding "brotli_module" to MOD_BROTLI_LDADD
checking whether to enable mod_brotli... shared (reallyall)
...
Building shared: mod_buffer.la mod_data.la mod_ratelimit.la mod_reqtimeout.la mod_ext_filter.la mod_request.la mod_include.la mod_filter.la mod_reflector.la mod_substitute.la mod_sed.la …
```
> Add missing libs for debian

- 2.4/Dockerfile
Debian Buster has been released as the new stable
Upgrade base image to Debian Buster. Debian Buster ships with openssl 1.1.1c-1 which provides TLS 1.3 support.
> Upgrade to debian:buster for TLS1.3 support

- 2.4/alpine/Dockerfile
Same as https://github.com/docker-library/httpd/pull/134 just adding `brotli-dev` to enable official module `mod_brotli`
> Enable mod_brotli support for Alpine repo

- 2.4/Dockerfile
Use the same hardening flags as the Debian build to enable RELRO,
stack protector and hardening.
Signed-off-by: Justin Cormack <justin.cormack@docker.com>
> Add hardening flags

- 2.4/Dockerfile
- 2.4/alpine/Dockerfile
See https://github.com/docker-library/php/issues/907
> Swap "WINCH" for "SIGWINCH" (which fixes containerd's ability to use this value)

- 2.4/alpine/Dockerfile
These lib files are not even a separate package in debian ([packages.debian.org](https://packages.debian.org/buster/amd64/libaprutil1/filelist) vs [pkgs.alpinelinux.org](https://pkgs.alpinelinux.org/contents?branch=v3.11&name=apr-util-dbm_db&arch=x86_64&repo=main)). They were added as recommends in Fedora ([bugzilla.redhat.com](https://bugzilla.redhat.com/show_bug.cgi?id=1491151) and [src.fedoreproject.org](https://src.fedoraproject.org/rpms/apr-util/c/7def96255723f89df0831670d8bd9a6be5a979c3))
It will be a slight increase in size (~112MB vs ~109MB)
Fixes #153
> Add apr-util-dbm_db to fix mod_dav

- 2.4/alpine/Dockerfile
I've noticed the alpine-based image has become almost twice as large (314 MB) as the debian-based image (166 MB).
Upon further investigation, I've found out several build dependencies are being included as part of the alpine-based image. Somehow, this became worse after the base image was upgraded to Alpine 3.12.
The following command can be run inside the container to determine which apk packages are included and how much space each one of them is taking: ``` apk info | xargs -n1 -I{} apk info -s {} | xargs -n4 | awk '{print $4,$1}' | sort -rn ```.
The output reveals several build dependencies such as llvm10-libs-10.0.0-r2 (~60.5 MB) and clang-libs-10.0.0-r2 (~60.0 MB) haven't been removed from the docker image.
This commit attempts to clean up unnecessary build dependencies from the …
> Remove build dependencies from image

- 2.4/Dockerfile
This commit will:
- add missing key hash and details for stefan@eissing.org
- update httpd version to 2.4.49
- update sha256
Additionally also uploaded the missing key to:
https://keyserver.ubuntu.com
(as it was missing, and the build failed previously)
> Update build to 2.4.49

- 2.4/Dockerfile
- 2.4/alpine/Dockerfile
Fixes https://github.com/docker-library/httpd/issues/214
> Move ca-certificates to runtime dependency

- 2.4/Dockerfile
This is pulled in automatically via `gnupg`, and moved from `Recommends` to `Depends` in https://salsa.debian.org/debian/gnupg2/-/commit/99474ad900a8bcdd0e7b68f986fec0013fc01470, which has been part of `src:gnupg2` since 2.1.21-4 (and every supported version of both Debian _and_ Ubuntu have 2.2.x 😇).
> Remove explicit `dirmngr` reference

- 2.4/Dockerfile
See https://apache.org/history/mirror-history.html
See also https://github.com/docker-library/tomcat/pull/308
> Update Apache project mirrors
